### ISSUE TITLE
Not makin' with the cats

### ISSUE THREAD

**Issue by AlinaMau** [MinecraftModDevelopmentMods/kitty-kats-staff#6]
I was sent over by ProxyNeko! I'm currently running a hand made modpack (not fully released yet XD) and when I finally made the wand I found that it didn't create anything but did display the cooldown as if it had. I know I have several mods that add mobs so I'm not sure if it's an ID conflict or an issue with the custom mob spawner mod.

Mod List (main mods anyway)

Aquaculture
ABwitchment
Bibliocraft
Biomes o plenty
Block craftery
Chisel
Custom Mob Spawner
Fossils and Archeology
Minions
Mo Creatures
Natura
Pams Harvestcraft
Plustic
Tinkers Construct
Thaumcraft
Tropicraft
Twilight Forest

There's other stuff but they're mostly small, add ons for other mods or waila, stuff like that. I tried to include anything that added mobs, effected mobs, or are just intensive on the game. If you feel like you need to know the rest let me know!

**Comment by KiriCattus** [comment]
I've tested all the above mods bar PlusTic and Block Craftery (I couldn't find those two) and had no issue in survival or creative, it may be one of the other mods in the pack, my suggestion would be cut the pack in half, test with the first half if it's not happening there then test with the other half and run by process of elimination.

**Comment by AlinaMau** [comment]
Well I'm not sure if it's because I've removed the right thing or because I was originally running an outdated version of the mod but she's working now! Thank you for looking and thank you for making such a cute mod X3 <3

**Comment by KiriCattus** [comment]
I can't remember if I had another release for that mod but I may have, the current build (1.0.0.5) didn't have the issues and that's the only one released at the moment but glad the issue is resolved :) Thanks for your kind words though :D
